version: "3.4"
services:
  app:
    container_name: "api"
    build:
      context: ""
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
    environment:
      PORT: 8090
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: vet
      SSL_MODE: disable
      GOOGLE_APPLICATION_CREDENTIALS: firebase-admin-sdk.json
    restart: always
    volumes:
      - api-data:/usr/src/app/
    networks:
      - api-backend

  postgres:
    container_name: "postgres"
    image: postgres:12.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: vet
      POSTGRES_PASSWORD: root
    restart: always
    networks:
      - api-backend

volumes:
  api-data:

networks:
  api-backend:
