name: Build Workflow

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    types: [ reopened ]

jobs:
  build:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'

      - name: Fetch dependencies
        run: |
          go get -u golang.org/x/lint/golint
          go get -v -t -d ./...

      - name: Build artifact
        run: go build .

      - name: Linter verifications
        run: |
          go vet .
          golint .

      - name: Extecute unit tests
        run: |
          go test -coverprofile cover.out ./...
          mkdir -p coverage && mv cover.out coverage

      - name: Fix code coverage paths
        working-directory: ./coverage
        run: |
          sed -i 's/\/home\/runner\/work\/vet-medical-history-api\/vet-medical-history-api\//\/github\/workspace\//g' cover.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
